#!/bin/bash
# nothing to do, yet.
set -eu

safe gen $CREDENTIALS/standalone/system password
safe gen $CREDENTIALS/standalone/system username
safe set $CREDENTIALS/standalone/database name="mysql"

exit 0
