meta:
  size: default
  admin_password: (( vault $CREDENTIALS "/mariadb/system:password" ))
  admin_username: (( vault $CREDENTIALS "/mariadb/system:username" ))

releases:
  - { name: mariadb-forge, version: latest }

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
  - name: standalone
    instances: 1
    azs: [z1]
    networks:
      - name: default
    stemcell: default

    vm_type: (( grab meta.size ))
    persistent_disk_type: default

    jobs:
    - name:    standalone
      release: mariadb-forge
      properties:
        db:
          admin_password: (( grab meta.admin_password ))
          admin_username: (( grab meta.admin_username ))
