---
meta:
  name:    mariadb-forge
  release: Blacksmith MariaDB Forge
  target:  blacksmith@pipes
  url:     https://cloudpipes.starkandwayne.com

  manifest:
    path: ci/manifest.yml

  git:
    name: Stark & Wayne CI Bot
    email: ci@starkandwayne.com

  bosh-lite:
    target:   ((thunder-dome.url))
    username: ((thunder-dome.username))
    password: ((thunder-dome.password))
    cacert:   ((thunder-dome.ca-certificate))

  aws:
    access_key: ((cfcommunity.access))
    secret_key: ((cfcommunity.secret))

  github:
    owner:  blacksmith-community
    repo:   mariadb-forge-boshrelease
    branch: master
    private_key:  ((starkandwayne-bot-github.private-key))
    access_token: ((starkandwayne-bot-github.access-token))

  shout:
    url:      ((shout.url))
    username: ((shout.username))
    password: ((shout.password))
